package com.ugg.authserver.mapper;

import com.ugg.authserver.entity.CrmMemberGift;
import com.ugg.authserver.entity.CrmMemberGiftExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrmMemberGiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member_gift
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    int countByExample(CrmMemberGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member_gift
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    int deleteByExample(CrmMemberGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member_gift
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member_gift
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    int insert(CrmMemberGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member_gift
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    int insertSelective(CrmMemberGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member_gift
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    List<CrmMemberGift> selectByExample(CrmMemberGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member_gift
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    CrmMemberGift selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member_gift
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") CrmMemberGift record, @Param("example") CrmMemberGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member_gift
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    int updateByExample(@Param("record") CrmMemberGift record, @Param("example") CrmMemberGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member_gift
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    int updateByPrimaryKeySelective(CrmMemberGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member_gift
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    int updateByPrimaryKey(CrmMemberGift record);
}