package com.ugg.authserver.mapper;

import com.ugg.authserver.entity.CrmSysAuthLog;
import com.ugg.authserver.entity.CrmSysAuthLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrmSysAuthLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_auth_log
     *
     * @mbggenerated Tue Jul 23 15:33:47 CST 2019
     */
    int countByExample(CrmSysAuthLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_auth_log
     *
     * @mbggenerated Tue Jul 23 15:33:47 CST 2019
     */
    int deleteByExample(CrmSysAuthLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_auth_log
     *
     * @mbggenerated Tue Jul 23 15:33:47 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_auth_log
     *
     * @mbggenerated Tue Jul 23 15:33:47 CST 2019
     */
    int insert(CrmSysAuthLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_auth_log
     *
     * @mbggenerated Tue Jul 23 15:33:47 CST 2019
     */
    int insertSelective(CrmSysAuthLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_auth_log
     *
     * @mbggenerated Tue Jul 23 15:33:47 CST 2019
     */
    List<CrmSysAuthLog> selectByExample(CrmSysAuthLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_auth_log
     *
     * @mbggenerated Tue Jul 23 15:33:47 CST 2019
     */
    CrmSysAuthLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_auth_log
     *
     * @mbggenerated Tue Jul 23 15:33:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") CrmSysAuthLog record, @Param("example") CrmSysAuthLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_auth_log
     *
     * @mbggenerated Tue Jul 23 15:33:47 CST 2019
     */
    int updateByExample(@Param("record") CrmSysAuthLog record, @Param("example") CrmSysAuthLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_auth_log
     *
     * @mbggenerated Tue Jul 23 15:33:47 CST 2019
     */
    int updateByPrimaryKeySelective(CrmSysAuthLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_auth_log
     *
     * @mbggenerated Tue Jul 23 15:33:47 CST 2019
     */
    int updateByPrimaryKey(CrmSysAuthLog record);
}