package com.ugg.authserver.mapper;

import com.ugg.authserver.entity.CrmSysUser;
import com.ugg.authserver.entity.CrmSysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrmSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_user
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    int countByExample(CrmSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_user
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    int deleteByExample(CrmSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_user
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_user
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    int insert(CrmSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_user
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    int insertSelective(CrmSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_user
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    List<CrmSysUser> selectByExample(CrmSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_user
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    CrmSysUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_user
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") CrmSysUser record, @Param("example") CrmSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_user
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    int updateByExample(@Param("record") CrmSysUser record, @Param("example") CrmSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_user
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    int updateByPrimaryKeySelective(CrmSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_user
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    int updateByPrimaryKey(CrmSysUser record);
}