package com.ugg.authserver.mapper;

import com.ugg.authserver.entity.CrmSysRole;
import com.ugg.authserver.entity.CrmSysRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrmSysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_role
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    int countByExample(CrmSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_role
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    int deleteByExample(CrmSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_role
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_role
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    int insert(CrmSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_role
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    int insertSelective(CrmSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_role
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    List<CrmSysRole> selectByExample(CrmSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_role
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    CrmSysRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_role
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") CrmSysRole record, @Param("example") CrmSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_role
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    int updateByExample(@Param("record") CrmSysRole record, @Param("example") CrmSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_role
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    int updateByPrimaryKeySelective(CrmSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sys_role
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    int updateByPrimaryKey(CrmSysRole record);
}