package com.ugg.authserver.entity;

import lombok.Data;

@Data
public class CrmMemberGift {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member_gift.id
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member_gift.member_id
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member_gift.send_time
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    private String sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member_gift.gift_type
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    private String giftType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member_gift.start_date
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member_gift.start_time
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member_gift.end_date
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member_gift.end_time
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member_gift.status
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member_gift.remark
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member_gift.is_delete
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member_gift.id
     *
     * @return the value of crm_member_gift.id
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member_gift.id
     *
     * @param id the value for crm_member_gift.id
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member_gift.member_id
     *
     * @return the value of crm_member_gift.member_id
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member_gift.member_id
     *
     * @param memberId the value for crm_member_gift.member_id
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member_gift.send_time
     *
     * @return the value of crm_member_gift.send_time
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public String getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member_gift.send_time
     *
     * @param sendTime the value for crm_member_gift.send_time
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public void setSendTime(String sendTime) {
        this.sendTime = sendTime == null ? null : sendTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member_gift.gift_type
     *
     * @return the value of crm_member_gift.gift_type
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public String getGiftType() {
        return giftType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member_gift.gift_type
     *
     * @param giftType the value for crm_member_gift.gift_type
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public void setGiftType(String giftType) {
        this.giftType = giftType == null ? null : giftType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member_gift.start_date
     *
     * @return the value of crm_member_gift.start_date
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member_gift.start_date
     *
     * @param startDate the value for crm_member_gift.start_date
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member_gift.start_time
     *
     * @return the value of crm_member_gift.start_time
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member_gift.start_time
     *
     * @param startTime the value for crm_member_gift.start_time
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member_gift.end_date
     *
     * @return the value of crm_member_gift.end_date
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member_gift.end_date
     *
     * @param endDate the value for crm_member_gift.end_date
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member_gift.end_time
     *
     * @return the value of crm_member_gift.end_time
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member_gift.end_time
     *
     * @param endTime the value for crm_member_gift.end_time
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member_gift.status
     *
     * @return the value of crm_member_gift.status
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member_gift.status
     *
     * @param status the value for crm_member_gift.status
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member_gift.remark
     *
     * @return the value of crm_member_gift.remark
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member_gift.remark
     *
     * @param remark the value for crm_member_gift.remark
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member_gift.is_delete
     *
     * @return the value of crm_member_gift.is_delete
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member_gift.is_delete
     *
     * @param isDelete the value for crm_member_gift.is_delete
     *
     * @mbggenerated Thu Jun 06 14:32:52 CST 2019
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}