package com.ugg.authserver.entity;

import java.util.Date;

public class CrmSysUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user_role.id
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user_role.role_id
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user_role.user_id
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user_role.version
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user_role.is_deleted
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user_role.create_user_id
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user_role.create_time
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user_role.update_user_id
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    private Integer updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user_role.update_time
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user_role.id
     *
     * @return the value of crm_sys_user_role.id
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user_role.id
     *
     * @param id the value for crm_sys_user_role.id
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user_role.role_id
     *
     * @return the value of crm_sys_user_role.role_id
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user_role.role_id
     *
     * @param roleId the value for crm_sys_user_role.role_id
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user_role.user_id
     *
     * @return the value of crm_sys_user_role.user_id
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user_role.user_id
     *
     * @param userId the value for crm_sys_user_role.user_id
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user_role.version
     *
     * @return the value of crm_sys_user_role.version
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user_role.version
     *
     * @param version the value for crm_sys_user_role.version
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user_role.is_deleted
     *
     * @return the value of crm_sys_user_role.is_deleted
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user_role.is_deleted
     *
     * @param isDeleted the value for crm_sys_user_role.is_deleted
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user_role.create_user_id
     *
     * @return the value of crm_sys_user_role.create_user_id
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user_role.create_user_id
     *
     * @param createUserId the value for crm_sys_user_role.create_user_id
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user_role.create_time
     *
     * @return the value of crm_sys_user_role.create_time
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user_role.create_time
     *
     * @param createTime the value for crm_sys_user_role.create_time
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user_role.update_user_id
     *
     * @return the value of crm_sys_user_role.update_user_id
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user_role.update_user_id
     *
     * @param updateUserId the value for crm_sys_user_role.update_user_id
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user_role.update_time
     *
     * @return the value of crm_sys_user_role.update_time
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user_role.update_time
     *
     * @param updateTime the value for crm_sys_user_role.update_time
     *
     * @mbggenerated Sat Jun 08 00:10:05 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}