package com.ugg.authserver.entity;

import java.util.Date;

public class CrmSysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user.id
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user.login_name
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user.login_password
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user.version
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user.is_deleted
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user.create_user_id
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user.create_time
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user.update_user_id
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    private Integer updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_user.update_time
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user.id
     *
     * @return the value of crm_sys_user.id
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user.id
     *
     * @param id the value for crm_sys_user.id
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user.login_name
     *
     * @return the value of crm_sys_user.login_name
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user.login_name
     *
     * @param loginName the value for crm_sys_user.login_name
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user.login_password
     *
     * @return the value of crm_sys_user.login_password
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user.login_password
     *
     * @param loginPassword the value for crm_sys_user.login_password
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user.version
     *
     * @return the value of crm_sys_user.version
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user.version
     *
     * @param version the value for crm_sys_user.version
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user.is_deleted
     *
     * @return the value of crm_sys_user.is_deleted
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user.is_deleted
     *
     * @param isDeleted the value for crm_sys_user.is_deleted
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user.create_user_id
     *
     * @return the value of crm_sys_user.create_user_id
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user.create_user_id
     *
     * @param createUserId the value for crm_sys_user.create_user_id
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user.create_time
     *
     * @return the value of crm_sys_user.create_time
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user.create_time
     *
     * @param createTime the value for crm_sys_user.create_time
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user.update_user_id
     *
     * @return the value of crm_sys_user.update_user_id
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user.update_user_id
     *
     * @param updateUserId the value for crm_sys_user.update_user_id
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_user.update_time
     *
     * @return the value of crm_sys_user.update_time
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_user.update_time
     *
     * @param updateTime the value for crm_sys_user.update_time
     *
     * @mbggenerated Fri Jun 07 15:32:20 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}