package com.ugg.authserver.entity;

import java.util.Date;

public class CrmSysRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_role.id
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_role.role_name
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_role.create_user_id
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_role.create_time
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_role.update_user_id
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    private Integer updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sys_role.update_time
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_role.id
     *
     * @return the value of crm_sys_role.id
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_role.id
     *
     * @param id the value for crm_sys_role.id
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_role.role_name
     *
     * @return the value of crm_sys_role.role_name
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_role.role_name
     *
     * @param roleName the value for crm_sys_role.role_name
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_role.create_user_id
     *
     * @return the value of crm_sys_role.create_user_id
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_role.create_user_id
     *
     * @param createUserId the value for crm_sys_role.create_user_id
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_role.create_time
     *
     * @return the value of crm_sys_role.create_time
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_role.create_time
     *
     * @param createTime the value for crm_sys_role.create_time
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_role.update_user_id
     *
     * @return the value of crm_sys_role.update_user_id
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_role.update_user_id
     *
     * @param updateUserId the value for crm_sys_role.update_user_id
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sys_role.update_time
     *
     * @return the value of crm_sys_role.update_time
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sys_role.update_time
     *
     * @param updateTime the value for crm_sys_role.update_time
     *
     * @mbggenerated Thu Jun 06 16:31:03 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}